### ISSUE TITLE
Remove jQuery from Ember

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#31]
# Goal / Issue

_Slim the package by removing unnecessary packages._

### Considerations

* [x] http://miguelcamba.com/blog/2017/04/11/the-future-of-embers-testing-and-the-beheading-of-jquery/
* [x] http://blog.shipshape.io/ember-without-jquery/

### Expected Behavior

Deployment package size is measurably smaller.

### Status

* [x] Awaiting upstream dependency merge  on https://github.com/Vestorly/torii/pull/399

**Comment by 0xadada** [comment]
Not important atm

**Comment by 0xadada** [comment]
mir w/ember 2.16
```
File sizes:
 - dist/assets/app-c7f814a9e15c77876789d20a238396b4.js: 1020.25 KB (250.8 KB gzipped)
 - dist/assets/mir-4837d5e571f9a730261822cc8157dfe4.js: 168.72 KB (30.47 KB gzipped)
 - dist/assets/mir-fastboot-8aa322aa9a4d0bf449028bdd20febc38.js: 1.61 KB (768 B gzipped)
 - dist/assets/vendor-d0ec74ed5e15deab54a988ecea8cbde2.js: 849.7 KB (220.74 KB gzipped)
 - dist/ember-fetch/fastboot-fetch-805e176077930c98aec5834ae48bd0f2.js: 283 B (199 B gzipped)
 - dist/service-worker-741217ba635373dd67e27ae9920850bd.js: 1.06 KB (583 B gzipped)
 - dist/assets/mir-b4c97f4664b7a7a3079024de980ab269.css: 155.67 KB (22.07 KB gzipped)
 - dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
```

**Comment by 0xadada** [comment]
mir w/Ember 3.0.0.beta.5 (ember-cli-uglify compress option off)
```
File sizes:
 - dist/assets/app-a9d292db54f26095aa3433822ef8166a.js: 1.09 MB (264.9 KB gzipped)
 - dist/assets/mir-38fcf5977d569264cda05d95c39ccf7a.css: 156.73 KB (22.19 KB gzipped)
 - dist/assets/mir-cd263dda9fdacf2dc2644d01a1d36f6d.js: 174.91 KB (31.02 KB gzipped)
 - dist/assets/mir-fastboot-8d7e0bcd77aa498bf3246d5730b0f28d.js: 1.35 KB (684 B gzipped)
 - dist/assets/vendor-7e8f2241c4ea977258ca3f6456722782.js: 943.02 KB (234.19 KB gzipped)
 - dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
 - dist/ember-fetch/fastboot-fetch-26feb13bd4d2d94dc5aeb065a5b840a5.js: 311 B (210 B gzipped)
 - dist/service-worker-6bf87ea227183a4ce790d00be515add9.js: 1.08 KB (582 B gzipped)
```

**Comment by 0xadada** [comment]
mir w/Ember 3.0.0.beta.5 (ember-cli-uglify compress option on)

```
File sizes:
 - dist/assets/app-e4ccf8219e51d78d3040f973273b428e.js: 1005.52 KB (242.68 KB gzipped)
 - dist/assets/vendor-e45d4fdeb0656f05e0d8d6b433e9e086.js: 832.12 KB (212.23 KB gzipped)
 - dist/assets/mir-8509da22708dea4402739864879b74e4.js: 171.6 KB (30.77 KB gzipped)
 - dist/assets/mir-fastboot-b23e59e6a8e02ecca46c7af7b05ea2f2.js: 1.31 KB (677 B gzipped)
 - dist/assets/mir-38fcf5977d569264cda05d95c39ccf7a.css: 156.73 KB (22.19 KB gzipped)
 - dist/service-worker-741217ba635373dd67e27ae9920850bd.js: 1.06 KB (582 B gzipped)
 - dist/ember-fetch/fastboot-fetch-805e176077930c98aec5834ae48bd0f2.js: 283 B (199 B gzipped)
 - dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
2,011.893 KB
```

**Comment by 0xadada** [comment]
mir w/Ember 3.0.0.beta.5 without jQuery

```
File sizes:
 - dist/assets/app-5e8329e46cc5e603192b137bbbba6b22.js: 950.74 KB (216.8 KB gzipped)
 - dist/assets/vendor-5dce95ba2e6a30a30e42b54c9ae901cd.js: 776.03 KB (186.06 KB gzipped)
 - dist/assets/mir-15022f33590076eb73cc4458dfa3fcde.js: 172.91 KB (31.09 KB gzipped)
 - dist/assets/mir-c6ed48a364df26e92118350737d38e27.css: 167.58 KB (22.74 KB gzipped)
 - dist/assets/mir-fastboot-74a791622fb4d7ecf82b913246d53a09.js: 1.3 KB (669 B gzipped)
 - dist/service-worker-741217ba635373dd67e27ae9920850bd.js: 1.06 KB (581 B gzipped)
 - dist/ember-fetch/fastboot-fetch-805e176077930c98aec5834ae48bd0f2.js: 283 B (199 B gzipped)
 - dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
```

**Comment by 0xadada** [comment]
`this.get('torii').open` rejects promise with  `"TypeError: Ember.$ is not a function"`

ember-simple-auth/authenticators/torii.js
```js
authenticate(provider, options) {
      this._assertToriiIsPresent();

      return this.get('torii').open(provider, options || {}).then(data => {
        this._authenticateWithProvider(provider, data);
        return data;
      });
    },
```

**Comment by 0xadada** [comment]
Override ajaxOptions to always set the `Content-Type`

app/adapters/application.js
```js
ajaxOptions() {
    const options = this._super(...arguments) || {};
    options.headers = options.headers || {};
    options.headers['Content-Type'] = 'application/vnd.api+json';
    return options;
}
```

**Comment by 0xadada** [comment]
"Application | media/new > authenticated user: can add and delete valid media"

Test failing on 
```
"Error: Assertion Failed: normalizeResponse must return a valid JSON API document:
	* One or more of the following keys must be present: "data", "errors", "meta".
    at new EmberError (http://localhost:4200/assets/vendor.js:13738:25)
    at Object.assert (http://localhost:4200/assets/vendor.js:13981:15)
    at normalizeResponseHelper (http://localhost:4200/assets/vendor.js:158279:56)
    at store._backburner.join (http://localhost:4200/assets/vendor.js:162650:19)
    at Backburner._run (http://localhost:4200/assets/vendor.js:10181:35)
    at Backburner._join (http://localhost:4200/assets/vendor.js:10159:29)
    at Backburner.join (http://localhost:4200/assets/vendor.js:9900:25)
    at promise.then.adapterPayload (http://localhost:4200/assets/vendor.js:162646:23)
    at tryCatcher (http://localhost:4200/assets/vendor.js:50837:21)
    at invokeCallback (http://localhost:4200/assets/vendor.js:51015:33)"
```

Mirage is failing on
```js
this.del('/medias/:id', (schema, request) => {
    let media = schema.medias.find(request.params.id);
    media.destroy();
  });
```

**Comment by 0xadada** [comment]
```
File sizes:
 - dist/assets/app-cfb0354eb02f6af9dfcf35a0a6d9f2ec.js: 921 KB (213.15 KB gzipped)
 - dist/assets/vendor-ea0013e392d4faf596780ab8ed2247cf.js: 747.28 KB (182.75 KB gzipped)
 - dist/assets/mir-0d3c13b1f62082875055935a315f629a.js: 171.92 KB (30.91 KB gzipped)
 - dist/assets/mir-38fcf5977d569264cda05d95c39ccf7a.css: 156.73 KB (22.19 KB gzipped)
 - dist/assets/mir-fastboot-b23e59e6a8e02ecca46c7af7b05ea2f2.js: 1.31 KB (677 B gzipped)
 - dist/service-worker-741217ba635373dd67e27ae9920850bd.js: 1.06 KB (583 B gzipped)
 - dist/ember-fetch/fastboot-fetch-805e176077930c98aec5834ae48bd0f2.js: 283 B (199 B gzipped)
 - dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
```

**Comment by 0xadada** [comment]
closed by https://github.com/mirai-audio/mir/pull/59

**Comment by 0xadada** [comment]
closed by https://github.com/mirai-audio/mir/pull/59
